# Generated by Django 5.1.4 on 2025-01-02 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='p_iva',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='VAT Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pec',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PEC Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sdi_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SDI Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Regular Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone'),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cell', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Role/Position')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
        ),
    ]
